// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv35YKlwxSwnkVZVZjweBsaA_J9qqytf8',
    appId: '1:928264708528:web:7187c54a2dab5119187675',
    messagingSenderId: '928264708528',
    projectId: 'todo2-a7bf5',
    authDomain: 'todo2-a7bf5.firebaseapp.com',
    storageBucket: 'todo2-a7bf5.appspot.com',
    measurementId: 'G-HQ3C5HX814',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO2nnZKBE831RpClXZuxpLn5fNZpHcL4g',
    appId: '1:928264708528:android:d8c1378d29c62150187675',
    messagingSenderId: '928264708528',
    projectId: 'todo2-a7bf5',
    storageBucket: 'todo2-a7bf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHSk8gOEibOI4vL_xlDxvFAVU6hAAZ5X0',
    appId: '1:928264708528:ios:852d6dd8558bb240187675',
    messagingSenderId: '928264708528',
    projectId: 'todo2-a7bf5',
    storageBucket: 'todo2-a7bf5.appspot.com',
    iosBundleId: 'com.example.todo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHSk8gOEibOI4vL_xlDxvFAVU6hAAZ5X0',
    appId: '1:928264708528:ios:852d6dd8558bb240187675',
    messagingSenderId: '928264708528',
    projectId: 'todo2-a7bf5',
    storageBucket: 'todo2-a7bf5.appspot.com',
    iosBundleId: 'com.example.todo2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv35YKlwxSwnkVZVZjweBsaA_J9qqytf8',
    appId: '1:928264708528:web:8fafd16e5165de47187675',
    messagingSenderId: '928264708528',
    projectId: 'todo2-a7bf5',
    authDomain: 'todo2-a7bf5.firebaseapp.com',
    storageBucket: 'todo2-a7bf5.appspot.com',
    measurementId: 'G-5RWWNSEJ6X',
  );
}
